appearance:
  default: system
  switcher: true

# Desert theme
theme:
  colorPalettes:
    default:
      - "#0d0887"
      - "#3e049c"
      - "#6300a7"
      - "#8606a6"
      - "#a62098"
      - "#c03a83"
      - "#d5546e"
      - "#e76f5a"
      - "#f68d45"
      - "#fdae32"
      - "#fcd225"
      - "#f0f921"
    wecaPaletteNew:
      dark:
        - "#40A832"
        - "#1D4F2B"
        - "#590075"
        - "#CE132D"
        - "#1F1F1F"
      light:
        - "#3C3C3C"
        - "#007D00"
        - "#8FCC87"
        - "#9C66AB"
        - "#ED8073"
        - "#A6A6A5"
        - "#FFFFFF"
  colors:
    primary:
      light: "#6300a7"  # Plasma Purple
      dark: "#6300a7"  # Plasma Purple
    accent:
      light: "#f68d45"  # Plasma Orange
      dark: "#f68d45"  # Plasma Orange  
    base:
      light: "#ffffff"  # White
      dark: "#000000"  # Black
    info:
      light: "#0d0887"  # Plasma Deep Blue
      dark: "#0d0887"  # Plasma Deep Blue
    warning:
      light: "#fcd225"  # Plasma Yellow
      dark: "#fcd225"  # Plasma Yellow
    negative:
      light: "#e76f5a"  # Plasma Red
      dark: "#e76f5a"  # Plasma Red
    positive:
      light: "#a62098"  # Plasma Magenta
      dark: "#a62098"  # Plasma Magenta

plugins:
  components:
    # This loads all of evidence's core charts and UI components
    # You probably don't want to edit this dependency unless you know what you are doing
    "@evidence-dev/core-components": {}

  datasources:
    # You can add additional datasources here by adding npm packages. 
    # Make to also add them to `package.json`.
    "@evidence-dev/bigquery": { }
    "@evidence-dev/csv": { }
    "@evidence-dev/databricks": { }
    "@evidence-dev/duckdb": { }
    "@evidence-dev/mssql": { }
    "@evidence-dev/mysql": { }
    "@evidence-dev/postgres": { }
    "@evidence-dev/source-javascript": { }
    "@evidence-dev/snowflake": { }
    "@evidence-dev/sqlite": { }
    "@evidence-dev/trino": { }
    "@evidence-dev/motherduck": { }
